// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1Spinner1 = lv_spinner_create(ui_Screen1, 1000, 90);
    lv_obj_set_width(ui_Screen1Spinner1, 80);
    lv_obj_set_height(ui_Screen1Spinner1, 80);
    lv_obj_set_align(ui_Screen1Spinner1, LV_ALIGN_CENTER);
    //设置为隐藏
    lv_obj_add_flag(ui_Screen1Spinner1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Screen1Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Screen1Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1Panel1, 300);
    lv_obj_set_height(ui_Screen1Panel1, 50);
    lv_obj_set_x(ui_Screen1Panel1, 0);
    lv_obj_set_y(ui_Screen1Panel1, -190);
    lv_obj_set_align(ui_Screen1Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1Panel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1Panel1, lv_color_hex(0xF4DCDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Screen1Switch1 = lv_switch_create(ui_Screen1Panel1);
    lv_obj_set_width(ui_Screen1Switch1, 50);
    lv_obj_set_height(ui_Screen1Switch1, 25);
    lv_obj_set_x(ui_Screen1Switch1, 110);
    lv_obj_set_y(ui_Screen1Switch1, 0);
    lv_obj_set_align(ui_Screen1Switch1, LV_ALIGN_CENTER);


    ui_Screen1Label1 = lv_label_create(ui_Screen1Panel1);
    lv_obj_set_width(ui_Screen1Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1Label1, -120);
    lv_obj_set_y(ui_Screen1Label1, 0);
    lv_obj_set_align(ui_Screen1Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1Label1, "WiFi");

    ui_Screen1ContainerScanResult = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Screen1ContainerScanResult);
    lv_obj_set_width(ui_Screen1ContainerScanResult, 300);
    lv_obj_set_height(ui_Screen1ContainerScanResult, 380);
    lv_obj_set_x(ui_Screen1ContainerScanResult, 0);
    lv_obj_set_y(ui_Screen1ContainerScanResult, 40);
    lv_obj_set_align(ui_Screen1ContainerScanResult, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1ContainerScanResult,
                    LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_clear_flag(ui_Screen1ContainerScanResult, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1ContainerScanResult, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1ContainerScanResult, lv_color_hex(0xF4DCDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1ContainerScanResult, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //设置为隐藏
    lv_obj_add_flag(ui_Screen1ContainerScanResult, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ResultContainer1 = lv_obj_create(ui_Screen1ContainerScanResult);
    lv_obj_remove_style_all(ui_ResultContainer1);
    lv_obj_set_width(ui_ResultContainer1, 280);
    lv_obj_set_height(ui_ResultContainer1, 50);
    lv_obj_set_x(ui_ResultContainer1, 10);
    lv_obj_set_y(ui_ResultContainer1, 10);
    lv_obj_clear_flag(ui_ResultContainer1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultContainer1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultContainer1, lv_color_hex(0xF5EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultContainer1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //设置为隐藏
    lv_obj_add_flag(ui_ResultContainer1, LV_OBJ_FLAG_HIDDEN);     /// Flags    

    ui_ResultLabel1 = lv_label_create(ui_ResultContainer1);
    lv_obj_set_width(ui_ResultLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResultLabel1, 5);
    lv_obj_set_y(ui_ResultLabel1, 0);
    lv_obj_set_align(ui_ResultLabel1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ResultLabel1, "WiFi Demo1");

    ui_ResultContainer2 = lv_obj_create(ui_Screen1ContainerScanResult);
    lv_obj_remove_style_all(ui_ResultContainer2);
    lv_obj_set_width(ui_ResultContainer2, 280);
    lv_obj_set_height(ui_ResultContainer2, 50);
    lv_obj_set_x(ui_ResultContainer2, 10);
    lv_obj_set_y(ui_ResultContainer2, 70);
    lv_obj_clear_flag(ui_ResultContainer2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultContainer2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultContainer2, lv_color_hex(0xF5EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultContainer2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //设置为隐藏
    lv_obj_add_flag(ui_ResultContainer2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ResultLabel2 = lv_label_create(ui_ResultContainer2);
    lv_obj_set_width(ui_ResultLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResultLabel2, 5);
    lv_obj_set_y(ui_ResultLabel2, 0);
    lv_obj_set_align(ui_ResultLabel2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ResultLabel2, "WiFi Demo1");

    ui_ResultContainer3 = lv_obj_create(ui_Screen1ContainerScanResult);
    lv_obj_remove_style_all(ui_ResultContainer3);
    lv_obj_set_width(ui_ResultContainer3, 280);
    lv_obj_set_height(ui_ResultContainer3, 50);
    lv_obj_set_x(ui_ResultContainer3, 10);
    lv_obj_set_y(ui_ResultContainer3, 130);
    lv_obj_clear_flag(ui_ResultContainer3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultContainer3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultContainer3, lv_color_hex(0xF5EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultContainer3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //设置为隐藏
    lv_obj_add_flag(ui_ResultContainer3, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ResultLabel3 = lv_label_create(ui_ResultContainer3);
    lv_obj_set_width(ui_ResultLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResultLabel3, 5);
    lv_obj_set_y(ui_ResultLabel3, 0);
    lv_obj_set_align(ui_ResultLabel3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ResultLabel3, "WiFi Demo1");

    ui_ResultContainer4 = lv_obj_create(ui_Screen1ContainerScanResult);
    lv_obj_remove_style_all(ui_ResultContainer4);
    lv_obj_set_width(ui_ResultContainer4, 280);
    lv_obj_set_height(ui_ResultContainer4, 50);
    lv_obj_set_x(ui_ResultContainer4, 10);
    lv_obj_set_y(ui_ResultContainer4, 190);
    lv_obj_clear_flag(ui_ResultContainer4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultContainer4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultContainer4, lv_color_hex(0xF5EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultContainer4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //设置为隐藏
    lv_obj_add_flag(ui_ResultContainer4, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ResultLabel4 = lv_label_create(ui_ResultContainer4);
    lv_obj_set_width(ui_ResultLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResultLabel4, 5);
    lv_obj_set_y(ui_ResultLabel4, 0);
    lv_obj_set_align(ui_ResultLabel4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ResultLabel4, "WiFi Demo1");

    ui_ResultContainer5 = lv_obj_create(ui_Screen1ContainerScanResult);
    lv_obj_remove_style_all(ui_ResultContainer5);
    lv_obj_set_width(ui_ResultContainer5, 280);
    lv_obj_set_height(ui_ResultContainer5, 50);
    lv_obj_set_x(ui_ResultContainer5, 10);
    lv_obj_set_y(ui_ResultContainer5, 250);
    lv_obj_clear_flag(ui_ResultContainer5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultContainer5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultContainer5, lv_color_hex(0xF5EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultContainer5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //设置为隐藏
    lv_obj_add_flag(ui_ResultContainer5, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ResultLabel5 = lv_label_create(ui_ResultContainer5);
    lv_obj_set_width(ui_ResultLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResultLabel5, 5);
    lv_obj_set_y(ui_ResultLabel5, 0);
    lv_obj_set_align(ui_ResultLabel5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ResultLabel5, "WiFi Demo1");

    ui_ResultContainer6 = lv_obj_create(ui_Screen1ContainerScanResult);
    lv_obj_remove_style_all(ui_ResultContainer6);
    lv_obj_set_width(ui_ResultContainer6, 280);
    lv_obj_set_height(ui_ResultContainer6, 50);
    lv_obj_set_x(ui_ResultContainer6, 10);
    lv_obj_set_y(ui_ResultContainer6, 310);
    lv_obj_clear_flag(ui_ResultContainer6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultContainer6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultContainer6, lv_color_hex(0xF5EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultContainer6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //设置为隐藏
    lv_obj_add_flag(ui_ResultContainer6, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ResultLabel6 = lv_label_create(ui_ResultContainer6);
    lv_obj_set_width(ui_ResultLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResultLabel6, 5);
    lv_obj_set_y(ui_ResultLabel6, 0);
    lv_obj_set_align(ui_ResultLabel6, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ResultLabel6, "WiFi Demo1");

    ui_ResultContainer7 = lv_obj_create(ui_Screen1ContainerScanResult);
    lv_obj_remove_style_all(ui_ResultContainer7);
    lv_obj_set_width(ui_ResultContainer7, 280);
    lv_obj_set_height(ui_ResultContainer7, 50);
    lv_obj_set_x(ui_ResultContainer7, 10);
    lv_obj_set_y(ui_ResultContainer7, 370);
    lv_obj_clear_flag(ui_ResultContainer7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultContainer7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultContainer7, lv_color_hex(0xF5EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultContainer7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //设置为隐藏
    lv_obj_add_flag(ui_ResultContainer7, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ResultLabel7 = lv_label_create(ui_ResultContainer7);
    lv_obj_set_width(ui_ResultLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResultLabel7, 5);
    lv_obj_set_y(ui_ResultLabel7, 0);
    lv_obj_set_align(ui_ResultLabel7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ResultLabel7, "WiFi Demo1");

    ui_ResultContainer8 = lv_obj_create(ui_Screen1ContainerScanResult);
    lv_obj_remove_style_all(ui_ResultContainer8);
    lv_obj_set_width(ui_ResultContainer8, 280);
    lv_obj_set_height(ui_ResultContainer8, 50);
    lv_obj_set_x(ui_ResultContainer8, 10);
    lv_obj_set_y(ui_ResultContainer8, 430);
    lv_obj_clear_flag(ui_ResultContainer8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultContainer8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultContainer8, lv_color_hex(0xF5EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultContainer8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //设置为隐藏
    lv_obj_add_flag(ui_ResultContainer8, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ResultLabel8 = lv_label_create(ui_ResultContainer8);
    lv_obj_set_width(ui_ResultLabel8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultLabel8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResultLabel8, 5);
    lv_obj_set_y(ui_ResultLabel8, 0);
    lv_obj_set_align(ui_ResultLabel8, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ResultLabel8, "WiFi Demo1");

    ui_ResultContainer9 = lv_obj_create(ui_Screen1ContainerScanResult);
    lv_obj_remove_style_all(ui_ResultContainer9);
    lv_obj_set_width(ui_ResultContainer9, 280);
    lv_obj_set_height(ui_ResultContainer9, 50);
    lv_obj_set_x(ui_ResultContainer9, 10);
    lv_obj_set_y(ui_ResultContainer9, 490);
    lv_obj_clear_flag(ui_ResultContainer9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultContainer9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultContainer9, lv_color_hex(0xF5EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultContainer9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //设置为隐藏
    lv_obj_add_flag(ui_ResultContainer9, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ResultLabel9 = lv_label_create(ui_ResultContainer9);
    lv_obj_set_width(ui_ResultLabel9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultLabel9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResultLabel9, 5);
    lv_obj_set_y(ui_ResultLabel9, 0);
    lv_obj_set_align(ui_ResultLabel9, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ResultLabel9, "WiFi Demo1");

    ui_ResultContainer10 = lv_obj_create(ui_Screen1ContainerScanResult);
    lv_obj_remove_style_all(ui_ResultContainer10);
    lv_obj_set_width(ui_ResultContainer10, 280);
    lv_obj_set_height(ui_ResultContainer10, 50);
    lv_obj_set_x(ui_ResultContainer10, 10);
    lv_obj_set_y(ui_ResultContainer10, 550);
    lv_obj_clear_flag(ui_ResultContainer10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultContainer10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultContainer10, lv_color_hex(0xF5EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultContainer10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //设置为隐藏
    lv_obj_add_flag(ui_ResultContainer10, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ResultLabel10 = lv_label_create(ui_ResultContainer10);
    lv_obj_set_width(ui_ResultLabel10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultLabel10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResultLabel10, 5);
    lv_obj_set_y(ui_ResultLabel10, 0);
    lv_obj_set_align(ui_ResultLabel10, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ResultLabel10, "WiFi Demo1");

    lv_obj_add_event_cb(ui_Screen1Switch1, ui_event_Screen1Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResultContainer1, ui_event_ResultContainer1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResultContainer2, ui_event_ResultContainer2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResultContainer3, ui_event_ResultContainer3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResultContainer4, ui_event_ResultContainer4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResultContainer5, ui_event_ResultContainer5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResultContainer6, ui_event_ResultContainer6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResultContainer7, ui_event_ResultContainer7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResultContainer8, ui_event_ResultContainer8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResultContainer9, ui_event_ResultContainer9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResultContainer10, ui_event_ResultContainer10, LV_EVENT_ALL, NULL);

}

extern wifi_ap_record_t ap_records[10];//wifi存储数据

void show_wifiResult_screen(int aps_count){
    //设置为显示
    lv_obj_clear_flag(ui_Screen1ContainerScanResult, LV_OBJ_FLAG_HIDDEN);     /// Flags
	//调用ui函数展示
    for (int i = 0; i < aps_count; i++)
    {
        char text[60] = {0};
        snprintf(text, sizeof(text), "%-20s\nCH:%3d RSSI:%3d db", ap_records[i].ssid, ap_records[i].primary, ap_records[i].rssi);
        switch (i+1)
        {
        case 1:
            lv_obj_clear_flag(ui_ResultContainer1, LV_OBJ_FLAG_HIDDEN);     /// Flags
            // lv_label_set_text(ui_ResultLabel1, (const char *)ap_records[i].ssid);
            lv_label_set_text(ui_ResultLabel1, text);
            break;
        case 2:
            lv_obj_clear_flag(ui_ResultContainer2, LV_OBJ_FLAG_HIDDEN);     /// Flags
            lv_label_set_text(ui_ResultLabel2, text);
            break;
        case 3:
            lv_obj_clear_flag(ui_ResultContainer3, LV_OBJ_FLAG_HIDDEN);     /// Flags
            lv_label_set_text(ui_ResultLabel3, text);
            break;
        case 4:
            lv_obj_clear_flag(ui_ResultContainer4, LV_OBJ_FLAG_HIDDEN);     /// Flags
            lv_label_set_text(ui_ResultLabel4, text);
            break;
        case 5:
            lv_obj_clear_flag(ui_ResultContainer5, LV_OBJ_FLAG_HIDDEN);     /// Flags
            lv_label_set_text(ui_ResultLabel5, text);
            break;
        case 6:
            lv_obj_clear_flag(ui_ResultContainer6, LV_OBJ_FLAG_HIDDEN);     /// Flags
            lv_label_set_text(ui_ResultLabel6, text);
            break;
        case 7:
            lv_obj_clear_flag(ui_ResultContainer7, LV_OBJ_FLAG_HIDDEN);     /// Flags
            lv_label_set_text(ui_ResultLabel7, text);
            break;
        case 8:
            lv_obj_clear_flag(ui_ResultContainer8, LV_OBJ_FLAG_HIDDEN);     /// Flags
            lv_label_set_text(ui_ResultLabel8, text);
            break;
        case 9:
            lv_obj_clear_flag(ui_ResultContainer9, LV_OBJ_FLAG_HIDDEN);     /// Flags
            lv_label_set_text(ui_ResultLabel9, text);
            break;
        case 10:
            lv_obj_clear_flag(ui_ResultContainer10, LV_OBJ_FLAG_HIDDEN);     /// Flags
            lv_label_set_text(ui_ResultLabel10, text);
            break;
        }
    }
}