// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include <stdio.h>
#include <string.h>

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen3Spinner1 = lv_spinner_create(ui_Screen3, 1000, 90);
    lv_obj_set_width(ui_Screen3Spinner1, 80);
    lv_obj_set_height(ui_Screen3Spinner1, 80);
    lv_obj_set_align(ui_Screen3Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen3Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Screen3ResultBTN1 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3ResultBTN1, 100);
    lv_obj_set_height(ui_Screen3ResultBTN1, 50);
    lv_obj_set_x(ui_Screen3ResultBTN1, 0);
    lv_obj_set_y(ui_Screen3ResultBTN1, 185);
    lv_obj_set_align(ui_Screen3ResultBTN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen3ResultBTN1, LV_OBJ_FLAG_HIDDEN);     /// 隐藏

    ui_Srceen3BTNLabel1 = lv_label_create(ui_Screen3ResultBTN1);
    lv_obj_set_width(ui_Srceen3BTNLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Srceen3BTNLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Srceen3BTNLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Srceen3BTNLabel1, "result");

    ui_Screen3WiFiInfoPanel = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3WiFiInfoPanel, 300);
    lv_obj_set_height(ui_Screen3WiFiInfoPanel, 300);
    lv_obj_set_align(ui_Screen3WiFiInfoPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen3WiFiInfoPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Screen3WiFiInfoPanel, LV_OBJ_FLAG_HIDDEN);     /// 隐藏

    ui_Screen3WiFiSSID = lv_label_create(ui_Screen3WiFiInfoPanel);
    lv_obj_set_width(ui_Screen3WiFiSSID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3WiFiSSID, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Screen3WiFiSSID, "SSID:");

    ui_Screen3WiFiPWD = lv_label_create(ui_Screen3WiFiInfoPanel);
    lv_obj_set_width(ui_Screen3WiFiPWD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3WiFiPWD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3WiFiPWD, 0);
    lv_obj_set_y(ui_Screen3WiFiPWD, 20);
    lv_label_set_text(ui_Screen3WiFiPWD, "PassWord:");

    ui_Screen3WiFiINFOLabel1 = lv_label_create(ui_Screen3WiFiInfoPanel);
    lv_obj_set_width(ui_Screen3WiFiINFOLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3WiFiINFOLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3WiFiINFOLabel1, 0);
    lv_obj_set_y(ui_Screen3WiFiINFOLabel1, 40);
    lv_label_set_text(ui_Screen3WiFiINFOLabel1, "INFO1");

    ui_Screen3WiFiINFOLabel2 = lv_label_create(ui_Screen3WiFiInfoPanel);
    lv_obj_set_width(ui_Screen3WiFiINFOLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3WiFiINFOLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3WiFiINFOLabel2, 0);
    lv_obj_set_y(ui_Screen3WiFiINFOLabel2, 60);
    lv_label_set_text(ui_Screen3WiFiINFOLabel2, "INFO2");

    lv_obj_add_event_cb(ui_Screen3ResultBTN1, ui_event_Srceen3BTNLabel1, LV_EVENT_ALL, NULL);

}

extern  char WIFI_SSID[50];
extern  char PASSWORD[50];
extern  char IPV4ADDR[20];
extern  char GATEWAY[20];

void show_wifi_info(void){

    lv_obj_clear_flag(ui_Screen3ResultBTN1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Screen3WiFiInfoPanel, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Screen3WiFiSSID, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Screen3WiFiPWD, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Screen3WiFiINFOLabel1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Screen3WiFiINFOLabel2, LV_OBJ_FLAG_HIDDEN);

    lv_label_set_text(ui_Screen3WiFiSSID,WIFI_SSID);
    lv_label_set_text(ui_Screen3WiFiPWD, PASSWORD);
    lv_label_set_text(ui_Screen3WiFiINFOLabel1, IPV4ADDR);
    lv_label_set_text(ui_Screen3WiFiINFOLabel2, GATEWAY);
}

void show_wifi_fail(void){
    lv_obj_clear_flag(ui_Screen3ResultBTN1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Screen3WiFiInfoPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags    
    lv_obj_add_flag(ui_Screen3WiFiPWD, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_add_flag(ui_Screen3WiFiINFOLabel1, LV_OBJ_FLAG_HIDDEN);     /// Flags    
    lv_obj_add_flag(ui_Screen3WiFiINFOLabel2, LV_OBJ_FLAG_HIDDEN);     /// Flags    

    lv_label_set_text(ui_Screen3WiFiSSID,"connected filed");
}