// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard1 = lv_keyboard_create(ui_Screen2);
    lv_obj_set_width(ui_Keyboard1, 320);
    lv_obj_set_height(ui_Keyboard1, 200);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 140);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_Screen2SSIDLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2SSIDLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2SSIDLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen2SSIDLabel, 0);
    lv_obj_set_y(ui_Screen2SSIDLabel, -200);
    lv_obj_set_align(ui_Screen2SSIDLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2SSIDLabel, "WiFi SSID");

    ui_Screen2PWDTextArea = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2PWDTextArea, 284);
    lv_obj_set_height(ui_Screen2PWDTextArea, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Screen2PWDTextArea, 0);
    lv_obj_set_y(ui_Screen2PWDTextArea, -84);
    lv_obj_set_align(ui_Screen2PWDTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_Screen2PWDTextArea, 20);
    lv_textarea_set_placeholder_text(ui_Screen2PWDTextArea, "Input PassWord Here...");
    lv_textarea_set_one_line(ui_Screen2PWDTextArea, true);


    lv_obj_set_style_text_font(ui_Screen2PWDTextArea, &lv_font_montserrat_16,
                               LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_Screen2ConnectBTN = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2ConnectBTN, 100);
    lv_obj_set_height(ui_Screen2ConnectBTN, 50);
    lv_obj_set_x(ui_Screen2ConnectBTN, 0);
    lv_obj_set_y(ui_Screen2ConnectBTN, -10);
    lv_obj_set_align(ui_Screen2ConnectBTN, LV_ALIGN_CENTER);

    ui_Screen2BTNLabel = lv_label_create(ui_Screen2ConnectBTN);
    lv_obj_set_width(ui_Screen2BTNLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2BTNLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen2BTNLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2BTNLabel, "Connet");

    lv_keyboard_set_textarea(ui_Keyboard1, ui_Screen2PWDTextArea);
    lv_obj_add_event_cb(ui_Screen2ConnectBTN, ui_event_Screen2ConnectBTN, LV_EVENT_ALL, NULL);

}
