// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "esp_wifi.h"
#include "esp_log.h"
#include "esp_err.h"

void showScanResult_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Screen1Spinner1;
extern lv_obj_t * ui_Screen1Panel1;
void ui_event_Screen1Switch1(lv_event_t * e);
extern lv_obj_t * ui_Screen1Switch1;
extern lv_obj_t * ui_Screen1Label1;
extern lv_obj_t * ui_Screen1ContainerScanResult;
void ui_event_ResultContainer1(lv_event_t * e);
extern lv_obj_t * ui_ResultContainer1;
extern lv_obj_t * ui_ResultLabel1;
void ui_event_ResultContainer2(lv_event_t * e);
extern lv_obj_t * ui_ResultContainer2;
extern lv_obj_t * ui_ResultLabel2;
void ui_event_ResultContainer3(lv_event_t * e);
extern lv_obj_t * ui_ResultContainer3;
extern lv_obj_t * ui_ResultLabel3;
void ui_event_ResultContainer4(lv_event_t * e);
extern lv_obj_t * ui_ResultContainer4;
extern lv_obj_t * ui_ResultLabel4;
void ui_event_ResultContainer5(lv_event_t * e);
extern lv_obj_t * ui_ResultContainer5;
extern lv_obj_t * ui_ResultLabel5;
void ui_event_ResultContainer6(lv_event_t * e);
extern lv_obj_t * ui_ResultContainer6;
extern lv_obj_t * ui_ResultLabel6;
void ui_event_ResultContainer7(lv_event_t * e);
extern lv_obj_t * ui_ResultContainer7;
extern lv_obj_t * ui_ResultLabel7;
void ui_event_ResultContainer8(lv_event_t * e);
extern lv_obj_t * ui_ResultContainer8;
extern lv_obj_t * ui_ResultLabel8;
void ui_event_ResultContainer9(lv_event_t * e);
extern lv_obj_t * ui_ResultContainer9;
extern lv_obj_t * ui_ResultLabel9;
void ui_event_ResultContainer10(lv_event_t * e);
extern lv_obj_t * ui_ResultContainer10;
extern lv_obj_t * ui_ResultLabel10;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_Screen2SSIDLabel;
extern lv_obj_t * ui_Screen2PWDTextArea;
void ui_event_Screen2ConnectBTN(lv_event_t * e);
extern lv_obj_t * ui_Screen2ConnectBTN;
extern lv_obj_t * ui_Screen2BTNLabel;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Screen3Spinner1;
extern lv_obj_t * ui_Screen3ResultBTN1;
void ui_event_Srceen3BTNLabel1(lv_event_t * e);
extern lv_obj_t * ui_Srceen3BTNLabel1;
extern lv_obj_t * ui_Screen3WiFiInfoPanel;
extern lv_obj_t * ui_Screen3WiFiSSID;
extern lv_obj_t * ui_Screen3WiFiPWD;
extern lv_obj_t * ui_Screen3WiFiINFOLabel1;
extern lv_obj_t * ui_Screen3WiFiINFOLabel2;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
