// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "wifi.h"

void wifi_open(lv_event_t * e)
{
	// Your code here
	wifi_start();
}

void wifi_close(lv_event_t * e)
{
	// Your code here
	wifi_stop();
}

extern wifi_ap_record_t ap_records[10];//wifi存储数据

void Screen1WiFiBTN(lv_event_t * e)
{
	lv_obj_t * target = lv_event_get_target(e);
	//跳转到第二屏
	_ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen2_screen_init);	
	//清空输入框
	lv_textarea_set_text(ui_Screen2PWDTextArea, "\0");
	//ToDo->调用函数 esp_wifi_get_xxx API 获取之前存储的配置信息
	if (target == ui_ResultContainer1)
	{
		lv_label_set_text(ui_Screen2SSIDLabel, (const char *)ap_records[0].ssid);
	}
	else if (target == ui_ResultContainer2)
	{
		lv_label_set_text(ui_Screen2SSIDLabel, (const char *)ap_records[1].ssid);
	}	
	else if (target == ui_ResultContainer3)
	{
		lv_label_set_text(ui_Screen2SSIDLabel, (const char *)ap_records[2].ssid);
	}	
	else if (target == ui_ResultContainer4)
	{
		lv_label_set_text(ui_Screen2SSIDLabel, (const char *)ap_records[3].ssid);
	}	
	else if (target == ui_ResultContainer5)
	{
		lv_label_set_text(ui_Screen2SSIDLabel, (const char *)ap_records[4].ssid);
	}	
	else if (target == ui_ResultContainer6)
	{
		lv_label_set_text(ui_Screen2SSIDLabel, (const char *)ap_records[5].ssid);
	}	
	else if (target == ui_ResultContainer7)
	{
		lv_label_set_text(ui_Screen2SSIDLabel, (const char *)ap_records[6].ssid);
	}	
	else if (target == ui_ResultContainer8)
	{
		lv_label_set_text(ui_Screen2SSIDLabel, (const char *)ap_records[7].ssid);
	}	
	else if (target == ui_ResultContainer9)
	{
		lv_label_set_text(ui_Screen2SSIDLabel, (const char *)ap_records[8].ssid);
	}	
	else if (target == ui_ResultContainer10)
	{
		lv_label_set_text(ui_Screen2SSIDLabel, (const char *)ap_records[9].ssid);
	}	
}

void Screen3BTNEvent(lv_event_t * e)
{
	// Your code here
}
